// <auto-generated />
using System;
using CSPOT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSPOT.Migrations
{
    [DbContext(typeof(QmCspotContext))]
    partial class QmCspotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CSPOT.Models.CspotDh3mrCspot2", b =>
                {
                    b.Property<DateTime?>("Ngày")
                        .HasColumnType("datetime");

                    b.Property<double?>("Tổng")
                        .HasColumnType("float");

                    b.Property<double?>("_0h30")
                        .HasColumnType("float")
                        .HasColumnName("0h30");

                    b.Property<double?>("_10h")
                        .HasColumnType("float")
                        .HasColumnName("10h");

                    b.Property<double?>("_10h30")
                        .HasColumnType("float")
                        .HasColumnName("10h30");

                    b.Property<double?>("_11h")
                        .HasColumnType("float")
                        .HasColumnName("11h");

                    b.Property<double?>("_11h30")
                        .HasColumnType("float")
                        .HasColumnName("11h30");

                    b.Property<double?>("_12h")
                        .HasColumnType("float")
                        .HasColumnName("12h");

                    b.Property<double?>("_12h30")
                        .HasColumnType("float")
                        .HasColumnName("12h30");

                    b.Property<double?>("_13h")
                        .HasColumnType("float")
                        .HasColumnName("13h");

                    b.Property<double?>("_13h30")
                        .HasColumnType("float")
                        .HasColumnName("13h30");

                    b.Property<double?>("_14h")
                        .HasColumnType("float")
                        .HasColumnName("14h");

                    b.Property<double?>("_14h30")
                        .HasColumnType("float")
                        .HasColumnName("14h30");

                    b.Property<double?>("_15h")
                        .HasColumnType("float")
                        .HasColumnName("15h");

                    b.Property<double?>("_15h30")
                        .HasColumnType("float")
                        .HasColumnName("15h30");

                    b.Property<double?>("_16h")
                        .HasColumnType("float")
                        .HasColumnName("16h");

                    b.Property<double?>("_16h30")
                        .HasColumnType("float")
                        .HasColumnName("16h30");

                    b.Property<double?>("_17h")
                        .HasColumnType("float")
                        .HasColumnName("17h");

                    b.Property<double?>("_17h30")
                        .HasColumnType("float")
                        .HasColumnName("17h30");

                    b.Property<double?>("_18h")
                        .HasColumnType("float")
                        .HasColumnName("18h");

                    b.Property<double?>("_18h30")
                        .HasColumnType("float")
                        .HasColumnName("18h30");

                    b.Property<double?>("_19h")
                        .HasColumnType("float")
                        .HasColumnName("19h");

                    b.Property<double?>("_19h30")
                        .HasColumnType("float")
                        .HasColumnName("19h30");

                    b.Property<double?>("_1h")
                        .HasColumnType("float")
                        .HasColumnName("1h");

                    b.Property<double?>("_1h30")
                        .HasColumnType("float")
                        .HasColumnName("1h30");

                    b.Property<double?>("_20h")
                        .HasColumnType("float")
                        .HasColumnName("20h");

                    b.Property<double?>("_20h30")
                        .HasColumnType("float")
                        .HasColumnName("20h30");

                    b.Property<double?>("_21h")
                        .HasColumnType("float")
                        .HasColumnName("21h");

                    b.Property<double?>("_21h30")
                        .HasColumnType("float")
                        .HasColumnName("21h30");

                    b.Property<double?>("_22h")
                        .HasColumnType("float")
                        .HasColumnName("22h");

                    b.Property<double?>("_22h30")
                        .HasColumnType("float")
                        .HasColumnName("22h30");

                    b.Property<double?>("_23h")
                        .HasColumnType("float")
                        .HasColumnName("23h");

                    b.Property<double?>("_23h30")
                        .HasColumnType("float")
                        .HasColumnName("23h30");

                    b.Property<double?>("_24h")
                        .HasColumnType("float")
                        .HasColumnName("24h");

                    b.Property<double?>("_2h")
                        .HasColumnType("float")
                        .HasColumnName("2h");

                    b.Property<double?>("_2h30")
                        .HasColumnType("float")
                        .HasColumnName("2h30");

                    b.Property<double?>("_3h")
                        .HasColumnType("float")
                        .HasColumnName("3h");

                    b.Property<double?>("_3h30")
                        .HasColumnType("float")
                        .HasColumnName("3h30");

                    b.Property<double?>("_4h")
                        .HasColumnType("float")
                        .HasColumnName("4h");

                    b.Property<double?>("_4h30")
                        .HasColumnType("float")
                        .HasColumnName("4h30");

                    b.Property<double?>("_5h")
                        .HasColumnType("float")
                        .HasColumnName("5h");

                    b.Property<double?>("_5h30")
                        .HasColumnType("float")
                        .HasColumnName("5h30");

                    b.Property<double?>("_6h")
                        .HasColumnType("float")
                        .HasColumnName("6h");

                    b.Property<double?>("_6h30")
                        .HasColumnType("float")
                        .HasColumnName("6h30");

                    b.Property<double?>("_7h")
                        .HasColumnType("float")
                        .HasColumnName("7h");

                    b.Property<double?>("_7h30")
                        .HasColumnType("float")
                        .HasColumnName("7h30");

                    b.Property<double?>("_8h")
                        .HasColumnType("float")
                        .HasColumnName("8h");

                    b.Property<double?>("_8h30")
                        .HasColumnType("float")
                        .HasColumnName("8h30");

                    b.Property<double?>("_9h")
                        .HasColumnType("float")
                        .HasColumnName("9h");

                    b.Property<double?>("_9h30")
                        .HasColumnType("float")
                        .HasColumnName("9h30");

                    b.ToTable("CspotDH3MR_Cspot2$$");
                });

            modelBuilder.Entity("CSPOT.Models.CspotPmCspot1", b =>
                {
                    b.Property<DateTime?>("Ngày")
                        .HasColumnType("datetime");

                    b.Property<double?>("Tổng")
                        .HasColumnType("float");

                    b.Property<double?>("_0h30")
                        .HasColumnType("float")
                        .HasColumnName("0h30");

                    b.Property<double?>("_10h")
                        .HasColumnType("float")
                        .HasColumnName("10h");

                    b.Property<double?>("_10h30")
                        .HasColumnType("float")
                        .HasColumnName("10h30");

                    b.Property<double?>("_11h")
                        .HasColumnType("float")
                        .HasColumnName("11h");

                    b.Property<double?>("_11h30")
                        .HasColumnType("float")
                        .HasColumnName("11h30");

                    b.Property<double?>("_12h")
                        .HasColumnType("float")
                        .HasColumnName("12h");

                    b.Property<double?>("_12h30")
                        .HasColumnType("float")
                        .HasColumnName("12h30");

                    b.Property<double?>("_13h")
                        .HasColumnType("float")
                        .HasColumnName("13h");

                    b.Property<double?>("_13h30")
                        .HasColumnType("float")
                        .HasColumnName("13h30");

                    b.Property<double?>("_14h")
                        .HasColumnType("float")
                        .HasColumnName("14h");

                    b.Property<double?>("_14h30")
                        .HasColumnType("float")
                        .HasColumnName("14h30");

                    b.Property<double?>("_15h")
                        .HasColumnType("float")
                        .HasColumnName("15h");

                    b.Property<double?>("_15h30")
                        .HasColumnType("float")
                        .HasColumnName("15h30");

                    b.Property<double?>("_16h")
                        .HasColumnType("float")
                        .HasColumnName("16h");

                    b.Property<double?>("_16h30")
                        .HasColumnType("float")
                        .HasColumnName("16h30");

                    b.Property<double?>("_17h")
                        .HasColumnType("float")
                        .HasColumnName("17h");

                    b.Property<double?>("_17h30")
                        .HasColumnType("float")
                        .HasColumnName("17h30");

                    b.Property<double?>("_18h")
                        .HasColumnType("float")
                        .HasColumnName("18h");

                    b.Property<double?>("_18h30")
                        .HasColumnType("float")
                        .HasColumnName("18h30");

                    b.Property<double?>("_19h")
                        .HasColumnType("float")
                        .HasColumnName("19h");

                    b.Property<double?>("_19h30")
                        .HasColumnType("float")
                        .HasColumnName("19h30");

                    b.Property<double?>("_1h")
                        .HasColumnType("float")
                        .HasColumnName("1h");

                    b.Property<double?>("_1h30")
                        .HasColumnType("float")
                        .HasColumnName("1h30");

                    b.Property<double?>("_20h")
                        .HasColumnType("float")
                        .HasColumnName("20h");

                    b.Property<double?>("_20h30")
                        .HasColumnType("float")
                        .HasColumnName("20h30");

                    b.Property<double?>("_21h")
                        .HasColumnType("float")
                        .HasColumnName("21h");

                    b.Property<double?>("_21h30")
                        .HasColumnType("float")
                        .HasColumnName("21h30");

                    b.Property<double?>("_22h")
                        .HasColumnType("float")
                        .HasColumnName("22h");

                    b.Property<double?>("_22h30")
                        .HasColumnType("float")
                        .HasColumnName("22h30");

                    b.Property<double?>("_23h")
                        .HasColumnType("float")
                        .HasColumnName("23h");

                    b.Property<double?>("_23h30")
                        .HasColumnType("float")
                        .HasColumnName("23h30");

                    b.Property<double?>("_24h")
                        .HasColumnType("float")
                        .HasColumnName("24h");

                    b.Property<double?>("_2h")
                        .HasColumnType("float")
                        .HasColumnName("2h");

                    b.Property<double?>("_2h30")
                        .HasColumnType("float")
                        .HasColumnName("2h30");

                    b.Property<double?>("_3h")
                        .HasColumnType("float")
                        .HasColumnName("3h");

                    b.Property<double?>("_3h30")
                        .HasColumnType("float")
                        .HasColumnName("3h30");

                    b.Property<double?>("_4h")
                        .HasColumnType("float")
                        .HasColumnName("4h");

                    b.Property<double?>("_4h30")
                        .HasColumnType("float")
                        .HasColumnName("4h30");

                    b.Property<double?>("_5h")
                        .HasColumnType("float")
                        .HasColumnName("5h");

                    b.Property<double?>("_5h30")
                        .HasColumnType("float")
                        .HasColumnName("5h30");

                    b.Property<double?>("_6h")
                        .HasColumnType("float")
                        .HasColumnName("6h");

                    b.Property<double?>("_6h30")
                        .HasColumnType("float")
                        .HasColumnName("6h30");

                    b.Property<double?>("_7h")
                        .HasColumnType("float")
                        .HasColumnName("7h");

                    b.Property<double?>("_7h30")
                        .HasColumnType("float")
                        .HasColumnName("7h30");

                    b.Property<double?>("_8h")
                        .HasColumnType("float")
                        .HasColumnName("8h");

                    b.Property<double?>("_8h30")
                        .HasColumnType("float")
                        .HasColumnName("8h30");

                    b.Property<double?>("_9h")
                        .HasColumnType("float")
                        .HasColumnName("9h");

                    b.Property<double?>("_9h30")
                        .HasColumnType("float")
                        .HasColumnName("9h30");

                    b.ToTable("CspotPM_Cspot1$$");
                });

            modelBuilder.Entity("CSPOT.Models.CspotTbCsport2", b =>
                {
                    b.Property<DateTime?>("Ngày")
                        .HasColumnType("datetime");

                    b.Property<double?>("Tổng")
                        .HasColumnType("float");

                    b.Property<double?>("_0h30")
                        .HasColumnType("float")
                        .HasColumnName("0h30");

                    b.Property<double?>("_10h")
                        .HasColumnType("float")
                        .HasColumnName("10h");

                    b.Property<double?>("_10h30")
                        .HasColumnType("float")
                        .HasColumnName("10h30");

                    b.Property<double?>("_11h")
                        .HasColumnType("float")
                        .HasColumnName("11h");

                    b.Property<double?>("_11h30")
                        .HasColumnType("float")
                        .HasColumnName("11h30");

                    b.Property<double?>("_12h")
                        .HasColumnType("float")
                        .HasColumnName("12h");

                    b.Property<double?>("_12h30")
                        .HasColumnType("float")
                        .HasColumnName("12h30");

                    b.Property<double?>("_13h")
                        .HasColumnType("float")
                        .HasColumnName("13h");

                    b.Property<double?>("_13h30")
                        .HasColumnType("float")
                        .HasColumnName("13h30");

                    b.Property<double?>("_14h")
                        .HasColumnType("float")
                        .HasColumnName("14h");

                    b.Property<double?>("_14h30")
                        .HasColumnType("float")
                        .HasColumnName("14h30");

                    b.Property<double?>("_15h")
                        .HasColumnType("float")
                        .HasColumnName("15h");

                    b.Property<double?>("_15h30")
                        .HasColumnType("float")
                        .HasColumnName("15h30");

                    b.Property<double?>("_16h")
                        .HasColumnType("float")
                        .HasColumnName("16h");

                    b.Property<double?>("_16h30")
                        .HasColumnType("float")
                        .HasColumnName("16h30");

                    b.Property<double?>("_17h")
                        .HasColumnType("float")
                        .HasColumnName("17h");

                    b.Property<double?>("_17h30")
                        .HasColumnType("float")
                        .HasColumnName("17h30");

                    b.Property<double?>("_18h")
                        .HasColumnType("float")
                        .HasColumnName("18h");

                    b.Property<double?>("_18h30")
                        .HasColumnType("float")
                        .HasColumnName("18h30");

                    b.Property<double?>("_19h")
                        .HasColumnType("float")
                        .HasColumnName("19h");

                    b.Property<double?>("_19h30")
                        .HasColumnType("float")
                        .HasColumnName("19h30");

                    b.Property<double?>("_1h")
                        .HasColumnType("float")
                        .HasColumnName("1h");

                    b.Property<double?>("_1h30")
                        .HasColumnType("float")
                        .HasColumnName("1h30");

                    b.Property<double?>("_20h")
                        .HasColumnType("float")
                        .HasColumnName("20h");

                    b.Property<double?>("_20h30")
                        .HasColumnType("float")
                        .HasColumnName("20h30");

                    b.Property<double?>("_21h")
                        .HasColumnType("float")
                        .HasColumnName("21h");

                    b.Property<double?>("_21h30")
                        .HasColumnType("float")
                        .HasColumnName("21h30");

                    b.Property<double?>("_22h")
                        .HasColumnType("float")
                        .HasColumnName("22h");

                    b.Property<double?>("_22h30")
                        .HasColumnType("float")
                        .HasColumnName("22h30");

                    b.Property<double?>("_23h")
                        .HasColumnType("float")
                        .HasColumnName("23h");

                    b.Property<double?>("_23h30")
                        .HasColumnType("float")
                        .HasColumnName("23h30");

                    b.Property<double?>("_24h")
                        .HasColumnType("float")
                        .HasColumnName("24h");

                    b.Property<double?>("_2h")
                        .HasColumnType("float")
                        .HasColumnName("2h");

                    b.Property<double?>("_2h30")
                        .HasColumnType("float")
                        .HasColumnName("2h30");

                    b.Property<double?>("_3h")
                        .HasColumnType("float")
                        .HasColumnName("3h");

                    b.Property<double?>("_3h30")
                        .HasColumnType("float")
                        .HasColumnName("3h30");

                    b.Property<double?>("_4h")
                        .HasColumnType("float")
                        .HasColumnName("4h");

                    b.Property<double?>("_4h30")
                        .HasColumnType("float")
                        .HasColumnName("4h30");

                    b.Property<double?>("_5h")
                        .HasColumnType("float")
                        .HasColumnName("5h");

                    b.Property<double?>("_5h30")
                        .HasColumnType("float")
                        .HasColumnName("5h30");

                    b.Property<double?>("_6h")
                        .HasColumnType("float")
                        .HasColumnName("6h");

                    b.Property<double?>("_6h30")
                        .HasColumnType("float")
                        .HasColumnName("6h30");

                    b.Property<double?>("_7h")
                        .HasColumnType("float")
                        .HasColumnName("7h");

                    b.Property<double?>("_7h30")
                        .HasColumnType("float")
                        .HasColumnName("7h30");

                    b.Property<double?>("_8h")
                        .HasColumnType("float")
                        .HasColumnName("8h");

                    b.Property<double?>("_8h30")
                        .HasColumnType("float")
                        .HasColumnName("8h30");

                    b.Property<double?>("_9h")
                        .HasColumnType("float")
                        .HasColumnName("9h");

                    b.Property<double?>("_9h30")
                        .HasColumnType("float")
                        .HasColumnName("9h30");

                    b.ToTable("CspotTB_Csport2$$");
                });

            modelBuilder.Entity("CSPOT.Models.CspotVt4Cspot2", b =>
                {
                    b.Property<DateTime?>("Ngày")
                        .HasColumnType("datetime");

                    b.Property<double?>("Tổng")
                        .HasColumnType("float");

                    b.Property<double?>("_0h30")
                        .HasColumnType("float")
                        .HasColumnName("0h30");

                    b.Property<double?>("_10h")
                        .HasColumnType("float")
                        .HasColumnName("10h");

                    b.Property<double?>("_10h30")
                        .HasColumnType("float")
                        .HasColumnName("10h30");

                    b.Property<double?>("_11h")
                        .HasColumnType("float")
                        .HasColumnName("11h");

                    b.Property<double?>("_11h30")
                        .HasColumnType("float")
                        .HasColumnName("11h30");

                    b.Property<double?>("_12h")
                        .HasColumnType("float")
                        .HasColumnName("12h");

                    b.Property<double?>("_12h30")
                        .HasColumnType("float")
                        .HasColumnName("12h30");

                    b.Property<double?>("_13h")
                        .HasColumnType("float")
                        .HasColumnName("13h");

                    b.Property<double?>("_13h30")
                        .HasColumnType("float")
                        .HasColumnName("13h30");

                    b.Property<double?>("_14h")
                        .HasColumnType("float")
                        .HasColumnName("14h");

                    b.Property<double?>("_14h30")
                        .HasColumnType("float")
                        .HasColumnName("14h30");

                    b.Property<double?>("_15h")
                        .HasColumnType("float")
                        .HasColumnName("15h");

                    b.Property<double?>("_15h30")
                        .HasColumnType("float")
                        .HasColumnName("15h30");

                    b.Property<double?>("_16h")
                        .HasColumnType("float")
                        .HasColumnName("16h");

                    b.Property<double?>("_16h30")
                        .HasColumnType("float")
                        .HasColumnName("16h30");

                    b.Property<double?>("_17h")
                        .HasColumnType("float")
                        .HasColumnName("17h");

                    b.Property<double?>("_17h30")
                        .HasColumnType("float")
                        .HasColumnName("17h30");

                    b.Property<double?>("_18h")
                        .HasColumnType("float")
                        .HasColumnName("18h");

                    b.Property<double?>("_18h30")
                        .HasColumnType("float")
                        .HasColumnName("18h30");

                    b.Property<double?>("_19h")
                        .HasColumnType("float")
                        .HasColumnName("19h");

                    b.Property<double?>("_19h30")
                        .HasColumnType("float")
                        .HasColumnName("19h30");

                    b.Property<double?>("_1h")
                        .HasColumnType("float")
                        .HasColumnName("1h");

                    b.Property<double?>("_1h30")
                        .HasColumnType("float")
                        .HasColumnName("1h30");

                    b.Property<double?>("_20h")
                        .HasColumnType("float")
                        .HasColumnName("20h");

                    b.Property<double?>("_20h30")
                        .HasColumnType("float")
                        .HasColumnName("20h30");

                    b.Property<double?>("_21h")
                        .HasColumnType("float")
                        .HasColumnName("21h");

                    b.Property<double?>("_21h30")
                        .HasColumnType("float")
                        .HasColumnName("21h30");

                    b.Property<double?>("_22h")
                        .HasColumnType("float")
                        .HasColumnName("22h");

                    b.Property<double?>("_22h30")
                        .HasColumnType("float")
                        .HasColumnName("22h30");

                    b.Property<double?>("_23h")
                        .HasColumnType("float")
                        .HasColumnName("23h");

                    b.Property<double?>("_23h30")
                        .HasColumnType("float")
                        .HasColumnName("23h30");

                    b.Property<double?>("_24h")
                        .HasColumnType("float")
                        .HasColumnName("24h");

                    b.Property<double?>("_2h")
                        .HasColumnType("float")
                        .HasColumnName("2h");

                    b.Property<double?>("_2h30")
                        .HasColumnType("float")
                        .HasColumnName("2h30");

                    b.Property<double?>("_3h")
                        .HasColumnType("float")
                        .HasColumnName("3h");

                    b.Property<double?>("_3h30")
                        .HasColumnType("float")
                        .HasColumnName("3h30");

                    b.Property<double?>("_4h")
                        .HasColumnType("float")
                        .HasColumnName("4h");

                    b.Property<double?>("_4h30")
                        .HasColumnType("float")
                        .HasColumnName("4h30");

                    b.Property<double?>("_5h")
                        .HasColumnType("float")
                        .HasColumnName("5h");

                    b.Property<double?>("_5h30")
                        .HasColumnType("float")
                        .HasColumnName("5h30");

                    b.Property<double?>("_6h")
                        .HasColumnType("float")
                        .HasColumnName("6h");

                    b.Property<double?>("_6h30")
                        .HasColumnType("float")
                        .HasColumnName("6h30");

                    b.Property<double?>("_7h")
                        .HasColumnType("float")
                        .HasColumnName("7h");

                    b.Property<double?>("_7h30")
                        .HasColumnType("float")
                        .HasColumnName("7h30");

                    b.Property<double?>("_8h")
                        .HasColumnType("float")
                        .HasColumnName("8h");

                    b.Property<double?>("_8h30")
                        .HasColumnType("float")
                        .HasColumnName("8h30");

                    b.Property<double?>("_9h")
                        .HasColumnType("float")
                        .HasColumnName("9h");

                    b.Property<double?>("_9h30")
                        .HasColumnType("float")
                        .HasColumnName("9h30");

                    b.ToTable("CspotVT4_Cspot2$$");
                });

            modelBuilder.Entity("CSPOT.Models.CspotVt4mrCspot2", b =>
                {
                    b.Property<DateTime?>("Ngày")
                        .HasColumnType("datetime");

                    b.Property<double?>("Tổng")
                        .HasColumnType("float");

                    b.Property<double?>("_0h30")
                        .HasColumnType("float")
                        .HasColumnName("0h30");

                    b.Property<double?>("_10h")
                        .HasColumnType("float")
                        .HasColumnName("10h");

                    b.Property<double?>("_10h30")
                        .HasColumnType("float")
                        .HasColumnName("10h30");

                    b.Property<double?>("_11h")
                        .HasColumnType("float")
                        .HasColumnName("11h");

                    b.Property<double?>("_11h30")
                        .HasColumnType("float")
                        .HasColumnName("11h30");

                    b.Property<double?>("_12h")
                        .HasColumnType("float")
                        .HasColumnName("12h");

                    b.Property<double?>("_12h30")
                        .HasColumnType("float")
                        .HasColumnName("12h30");

                    b.Property<double?>("_13h")
                        .HasColumnType("float")
                        .HasColumnName("13h");

                    b.Property<double?>("_13h30")
                        .HasColumnType("float")
                        .HasColumnName("13h30");

                    b.Property<double?>("_14h")
                        .HasColumnType("float")
                        .HasColumnName("14h");

                    b.Property<double?>("_14h30")
                        .HasColumnType("float")
                        .HasColumnName("14h30");

                    b.Property<double?>("_15h")
                        .HasColumnType("float")
                        .HasColumnName("15h");

                    b.Property<double?>("_15h30")
                        .HasColumnType("float")
                        .HasColumnName("15h30");

                    b.Property<double?>("_16h")
                        .HasColumnType("float")
                        .HasColumnName("16h");

                    b.Property<double?>("_16h30")
                        .HasColumnType("float")
                        .HasColumnName("16h30");

                    b.Property<double?>("_17h")
                        .HasColumnType("float")
                        .HasColumnName("17h");

                    b.Property<double?>("_17h30")
                        .HasColumnType("float")
                        .HasColumnName("17h30");

                    b.Property<double?>("_18h")
                        .HasColumnType("float")
                        .HasColumnName("18h");

                    b.Property<double?>("_18h30")
                        .HasColumnType("float")
                        .HasColumnName("18h30");

                    b.Property<double?>("_19h")
                        .HasColumnType("float")
                        .HasColumnName("19h");

                    b.Property<double?>("_19h30")
                        .HasColumnType("float")
                        .HasColumnName("19h30");

                    b.Property<double?>("_1h")
                        .HasColumnType("float")
                        .HasColumnName("1h");

                    b.Property<double?>("_1h30")
                        .HasColumnType("float")
                        .HasColumnName("1h30");

                    b.Property<double?>("_20h")
                        .HasColumnType("float")
                        .HasColumnName("20h");

                    b.Property<double?>("_20h30")
                        .HasColumnType("float")
                        .HasColumnName("20h30");

                    b.Property<double?>("_21h")
                        .HasColumnType("float")
                        .HasColumnName("21h");

                    b.Property<double?>("_21h30")
                        .HasColumnType("float")
                        .HasColumnName("21h30");

                    b.Property<double?>("_22h")
                        .HasColumnType("float")
                        .HasColumnName("22h");

                    b.Property<double?>("_22h30")
                        .HasColumnType("float")
                        .HasColumnName("22h30");

                    b.Property<double?>("_23h")
                        .HasColumnType("float")
                        .HasColumnName("23h");

                    b.Property<double?>("_23h30")
                        .HasColumnType("float")
                        .HasColumnName("23h30");

                    b.Property<double?>("_24h")
                        .HasColumnType("float")
                        .HasColumnName("24h");

                    b.Property<double?>("_2h")
                        .HasColumnType("float")
                        .HasColumnName("2h");

                    b.Property<double?>("_2h30")
                        .HasColumnType("float")
                        .HasColumnName("2h30");

                    b.Property<double?>("_3h")
                        .HasColumnType("float")
                        .HasColumnName("3h");

                    b.Property<double?>("_3h30")
                        .HasColumnType("float")
                        .HasColumnName("3h30");

                    b.Property<double?>("_4h")
                        .HasColumnType("float")
                        .HasColumnName("4h");

                    b.Property<double?>("_4h30")
                        .HasColumnType("float")
                        .HasColumnName("4h30");

                    b.Property<double?>("_5h")
                        .HasColumnType("float")
                        .HasColumnName("5h");

                    b.Property<double?>("_5h30")
                        .HasColumnType("float")
                        .HasColumnName("5h30");

                    b.Property<double?>("_6h")
                        .HasColumnType("float")
                        .HasColumnName("6h");

                    b.Property<double?>("_6h30")
                        .HasColumnType("float")
                        .HasColumnName("6h30");

                    b.Property<double?>("_7h")
                        .HasColumnType("float")
                        .HasColumnName("7h");

                    b.Property<double?>("_7h30")
                        .HasColumnType("float")
                        .HasColumnName("7h30");

                    b.Property<double?>("_8h")
                        .HasColumnType("float")
                        .HasColumnName("8h");

                    b.Property<double?>("_8h30")
                        .HasColumnType("float")
                        .HasColumnName("8h30");

                    b.Property<double?>("_9h")
                        .HasColumnType("float")
                        .HasColumnName("9h");

                    b.Property<double?>("_9h30")
                        .HasColumnType("float")
                        .HasColumnName("9h30");

                    b.ToTable("CspotVT4MR_Cspot2$$");
                });

            modelBuilder.Entity("CSPOT.Models.PmCspot1", b =>
                {
                    b.Property<DateTime?>("Ngày")
                        .HasColumnType("datetime");

                    b.Property<double?>("Tổng")
                        .HasColumnType("float");

                    b.Property<double?>("_0h30")
                        .HasColumnType("float")
                        .HasColumnName("0h30");

                    b.Property<double?>("_10h")
                        .HasColumnType("float")
                        .HasColumnName("10h");

                    b.Property<double?>("_10h30")
                        .HasColumnType("float")
                        .HasColumnName("10h30");

                    b.Property<double?>("_11h")
                        .HasColumnType("float")
                        .HasColumnName("11h");

                    b.Property<double?>("_11h30")
                        .HasColumnType("float")
                        .HasColumnName("11h30");

                    b.Property<double?>("_12h")
                        .HasColumnType("float")
                        .HasColumnName("12h");

                    b.Property<double?>("_12h30")
                        .HasColumnType("float")
                        .HasColumnName("12h30");

                    b.Property<double?>("_13h")
                        .HasColumnType("float")
                        .HasColumnName("13h");

                    b.Property<double?>("_13h30")
                        .HasColumnType("float")
                        .HasColumnName("13h30");

                    b.Property<double?>("_14h")
                        .HasColumnType("float")
                        .HasColumnName("14h");

                    b.Property<double?>("_14h30")
                        .HasColumnType("float")
                        .HasColumnName("14h30");

                    b.Property<double?>("_15h")
                        .HasColumnType("float")
                        .HasColumnName("15h");

                    b.Property<double?>("_15h30")
                        .HasColumnType("float")
                        .HasColumnName("15h30");

                    b.Property<double?>("_16h")
                        .HasColumnType("float")
                        .HasColumnName("16h");

                    b.Property<double?>("_16h30")
                        .HasColumnType("float")
                        .HasColumnName("16h30");

                    b.Property<double?>("_17h")
                        .HasColumnType("float")
                        .HasColumnName("17h");

                    b.Property<double?>("_17h30")
                        .HasColumnType("float")
                        .HasColumnName("17h30");

                    b.Property<double?>("_18h")
                        .HasColumnType("float")
                        .HasColumnName("18h");

                    b.Property<double?>("_18h30")
                        .HasColumnType("float")
                        .HasColumnName("18h30");

                    b.Property<double?>("_19h")
                        .HasColumnType("float")
                        .HasColumnName("19h");

                    b.Property<double?>("_19h30")
                        .HasColumnType("float")
                        .HasColumnName("19h30");

                    b.Property<double?>("_1h")
                        .HasColumnType("float")
                        .HasColumnName("1h");

                    b.Property<double?>("_1h30")
                        .HasColumnType("float")
                        .HasColumnName("1h30");

                    b.Property<double?>("_20h")
                        .HasColumnType("float")
                        .HasColumnName("20h");

                    b.Property<double?>("_20h30")
                        .HasColumnType("float")
                        .HasColumnName("20h30");

                    b.Property<double?>("_21h")
                        .HasColumnType("float")
                        .HasColumnName("21h");

                    b.Property<double?>("_21h30")
                        .HasColumnType("float")
                        .HasColumnName("21h30");

                    b.Property<double?>("_22h")
                        .HasColumnType("float")
                        .HasColumnName("22h");

                    b.Property<double?>("_22h30")
                        .HasColumnType("float")
                        .HasColumnName("22h30");

                    b.Property<double?>("_23h")
                        .HasColumnType("float")
                        .HasColumnName("23h");

                    b.Property<double?>("_23h30")
                        .HasColumnType("float")
                        .HasColumnName("23h30");

                    b.Property<double?>("_24h")
                        .HasColumnType("float")
                        .HasColumnName("24h");

                    b.Property<double?>("_2h")
                        .HasColumnType("float")
                        .HasColumnName("2h");

                    b.Property<double?>("_2h30")
                        .HasColumnType("float")
                        .HasColumnName("2h30");

                    b.Property<double?>("_3h")
                        .HasColumnType("float")
                        .HasColumnName("3h");

                    b.Property<double?>("_3h30")
                        .HasColumnType("float")
                        .HasColumnName("3h30");

                    b.Property<double?>("_4h")
                        .HasColumnType("float")
                        .HasColumnName("4h");

                    b.Property<double?>("_4h30")
                        .HasColumnType("float")
                        .HasColumnName("4h30");

                    b.Property<double?>("_5h")
                        .HasColumnType("float")
                        .HasColumnName("5h");

                    b.Property<double?>("_5h30")
                        .HasColumnType("float")
                        .HasColumnName("5h30");

                    b.Property<double?>("_6h")
                        .HasColumnType("float")
                        .HasColumnName("6h");

                    b.Property<double?>("_6h30")
                        .HasColumnType("float")
                        .HasColumnName("6h30");

                    b.Property<double?>("_7h")
                        .HasColumnType("float")
                        .HasColumnName("7h");

                    b.Property<double?>("_7h30")
                        .HasColumnType("float")
                        .HasColumnName("7h30");

                    b.Property<double?>("_8h")
                        .HasColumnType("float")
                        .HasColumnName("8h");

                    b.Property<double?>("_8h30")
                        .HasColumnType("float")
                        .HasColumnName("8h30");

                    b.Property<double?>("_9h")
                        .HasColumnType("float")
                        .HasColumnName("9h");

                    b.Property<double?>("_9h30")
                        .HasColumnType("float")
                        .HasColumnName("9h30");

                    b.ToTable("Pm_Cspot1$$");
                });

            modelBuilder.Entity("CSPOT.Models.PmCspot2", b =>
                {
                    b.Property<DateTime?>("Ngày")
                        .HasColumnType("datetime");

                    b.Property<double?>("Tổng")
                        .HasColumnType("float");

                    b.Property<double?>("_0h30")
                        .HasColumnType("float")
                        .HasColumnName("0h30");

                    b.Property<double?>("_10h")
                        .HasColumnType("float")
                        .HasColumnName("10h");

                    b.Property<double?>("_10h30")
                        .HasColumnType("float")
                        .HasColumnName("10h30");

                    b.Property<double?>("_11h")
                        .HasColumnType("float")
                        .HasColumnName("11h");

                    b.Property<double?>("_11h30")
                        .HasColumnType("float")
                        .HasColumnName("11h30");

                    b.Property<double?>("_12h")
                        .HasColumnType("float")
                        .HasColumnName("12h");

                    b.Property<double?>("_12h30")
                        .HasColumnType("float")
                        .HasColumnName("12h30");

                    b.Property<double?>("_13h")
                        .HasColumnType("float")
                        .HasColumnName("13h");

                    b.Property<double?>("_13h30")
                        .HasColumnType("float")
                        .HasColumnName("13h30");

                    b.Property<double?>("_14h")
                        .HasColumnType("float")
                        .HasColumnName("14h");

                    b.Property<double?>("_14h30")
                        .HasColumnType("float")
                        .HasColumnName("14h30");

                    b.Property<double?>("_15h")
                        .HasColumnType("float")
                        .HasColumnName("15h");

                    b.Property<double?>("_15h30")
                        .HasColumnType("float")
                        .HasColumnName("15h30");

                    b.Property<double?>("_16h")
                        .HasColumnType("float")
                        .HasColumnName("16h");

                    b.Property<double?>("_16h30")
                        .HasColumnType("float")
                        .HasColumnName("16h30");

                    b.Property<double?>("_17h")
                        .HasColumnType("float")
                        .HasColumnName("17h");

                    b.Property<double?>("_17h30")
                        .HasColumnType("float")
                        .HasColumnName("17h30");

                    b.Property<double?>("_18h")
                        .HasColumnType("float")
                        .HasColumnName("18h");

                    b.Property<double?>("_18h30")
                        .HasColumnType("float")
                        .HasColumnName("18h30");

                    b.Property<double?>("_19h")
                        .HasColumnType("float")
                        .HasColumnName("19h");

                    b.Property<double?>("_19h30")
                        .HasColumnType("float")
                        .HasColumnName("19h30");

                    b.Property<double?>("_1h")
                        .HasColumnType("float")
                        .HasColumnName("1h");

                    b.Property<double?>("_1h30")
                        .HasColumnType("float")
                        .HasColumnName("1h30");

                    b.Property<double?>("_20h")
                        .HasColumnType("float")
                        .HasColumnName("20h");

                    b.Property<double?>("_20h30")
                        .HasColumnType("float")
                        .HasColumnName("20h30");

                    b.Property<double?>("_21h")
                        .HasColumnType("float")
                        .HasColumnName("21h");

                    b.Property<double?>("_21h30")
                        .HasColumnType("float")
                        .HasColumnName("21h30");

                    b.Property<double?>("_22h")
                        .HasColumnType("float")
                        .HasColumnName("22h");

                    b.Property<double?>("_22h30")
                        .HasColumnType("float")
                        .HasColumnName("22h30");

                    b.Property<double?>("_23h")
                        .HasColumnType("float")
                        .HasColumnName("23h");

                    b.Property<double?>("_23h30")
                        .HasColumnType("float")
                        .HasColumnName("23h30");

                    b.Property<double?>("_24h")
                        .HasColumnType("float")
                        .HasColumnName("24h");

                    b.Property<double?>("_2h")
                        .HasColumnType("float")
                        .HasColumnName("2h");

                    b.Property<double?>("_2h30")
                        .HasColumnType("float")
                        .HasColumnName("2h30");

                    b.Property<double?>("_3h")
                        .HasColumnType("float")
                        .HasColumnName("3h");

                    b.Property<double?>("_3h30")
                        .HasColumnType("float")
                        .HasColumnName("3h30");

                    b.Property<double?>("_4h")
                        .HasColumnType("float")
                        .HasColumnName("4h");

                    b.Property<double?>("_4h30")
                        .HasColumnType("float")
                        .HasColumnName("4h30");

                    b.Property<double?>("_5h")
                        .HasColumnType("float")
                        .HasColumnName("5h");

                    b.Property<double?>("_5h30")
                        .HasColumnType("float")
                        .HasColumnName("5h30");

                    b.Property<double?>("_6h")
                        .HasColumnType("float")
                        .HasColumnName("6h");

                    b.Property<double?>("_6h30")
                        .HasColumnType("float")
                        .HasColumnName("6h30");

                    b.Property<double?>("_7h")
                        .HasColumnType("float")
                        .HasColumnName("7h");

                    b.Property<double?>("_7h30")
                        .HasColumnType("float")
                        .HasColumnName("7h30");

                    b.Property<double?>("_8h")
                        .HasColumnType("float")
                        .HasColumnName("8h");

                    b.Property<double?>("_8h30")
                        .HasColumnType("float")
                        .HasColumnName("8h30");

                    b.Property<double?>("_9h")
                        .HasColumnType("float")
                        .HasColumnName("9h");

                    b.Property<double?>("_9h30")
                        .HasColumnType("float")
                        .HasColumnName("9h30");

                    b.ToTable("Pm_Cspot2$$");
                });

            modelBuilder.Entity("CSPOT.Models.Qm1Cspot1", b =>
                {
                    b.Property<DateTime?>("Ngày")
                        .HasColumnType("datetime");

                    b.Property<double?>("Tổng")
                        .HasColumnType("float");

                    b.Property<double?>("_0h30")
                        .HasColumnType("float")
                        .HasColumnName("0h30");

                    b.Property<double?>("_10h")
                        .HasColumnType("float")
                        .HasColumnName("10h");

                    b.Property<double?>("_10h30")
                        .HasColumnType("float")
                        .HasColumnName("10h30");

                    b.Property<double?>("_11h")
                        .HasColumnType("float")
                        .HasColumnName("11h");

                    b.Property<double?>("_11h30")
                        .HasColumnType("float")
                        .HasColumnName("11h30");

                    b.Property<double?>("_12h")
                        .HasColumnType("float")
                        .HasColumnName("12h");

                    b.Property<double?>("_12h30")
                        .HasColumnType("float")
                        .HasColumnName("12h30");

                    b.Property<double?>("_13h")
                        .HasColumnType("float")
                        .HasColumnName("13h");

                    b.Property<double?>("_13h30")
                        .HasColumnType("float")
                        .HasColumnName("13h30");

                    b.Property<double?>("_14h")
                        .HasColumnType("float")
                        .HasColumnName("14h");

                    b.Property<double?>("_14h30")
                        .HasColumnType("float")
                        .HasColumnName("14h30");

                    b.Property<double?>("_15h")
                        .HasColumnType("float")
                        .HasColumnName("15h");

                    b.Property<double?>("_15h30")
                        .HasColumnType("float")
                        .HasColumnName("15h30");

                    b.Property<double?>("_16h")
                        .HasColumnType("float")
                        .HasColumnName("16h");

                    b.Property<double?>("_16h30")
                        .HasColumnType("float")
                        .HasColumnName("16h30");

                    b.Property<double?>("_17h")
                        .HasColumnType("float")
                        .HasColumnName("17h");

                    b.Property<double?>("_17h30")
                        .HasColumnType("float")
                        .HasColumnName("17h30");

                    b.Property<double?>("_18h")
                        .HasColumnType("float")
                        .HasColumnName("18h");

                    b.Property<double?>("_18h30")
                        .HasColumnType("float")
                        .HasColumnName("18h30");

                    b.Property<double?>("_19h")
                        .HasColumnType("float")
                        .HasColumnName("19h");

                    b.Property<double?>("_19h30")
                        .HasColumnType("float")
                        .HasColumnName("19h30");

                    b.Property<double?>("_1h")
                        .HasColumnType("float")
                        .HasColumnName("1h");

                    b.Property<double?>("_1h30")
                        .HasColumnType("float")
                        .HasColumnName("1h30");

                    b.Property<double?>("_20h")
                        .HasColumnType("float")
                        .HasColumnName("20h");

                    b.Property<double?>("_20h30")
                        .HasColumnType("float")
                        .HasColumnName("20h30");

                    b.Property<double?>("_21h")
                        .HasColumnType("float")
                        .HasColumnName("21h");

                    b.Property<double?>("_21h30")
                        .HasColumnType("float")
                        .HasColumnName("21h30");

                    b.Property<double?>("_22h")
                        .HasColumnType("float")
                        .HasColumnName("22h");

                    b.Property<double?>("_22h30")
                        .HasColumnType("float")
                        .HasColumnName("22h30");

                    b.Property<double?>("_23h")
                        .HasColumnType("float")
                        .HasColumnName("23h");

                    b.Property<double?>("_23h30")
                        .HasColumnType("float")
                        .HasColumnName("23h30");

                    b.Property<double?>("_24h")
                        .HasColumnType("float")
                        .HasColumnName("24h");

                    b.Property<double?>("_2h")
                        .HasColumnType("float")
                        .HasColumnName("2h");

                    b.Property<double?>("_2h30")
                        .HasColumnType("float")
                        .HasColumnName("2h30");

                    b.Property<double?>("_3h")
                        .HasColumnType("float")
                        .HasColumnName("3h");

                    b.Property<double?>("_3h30")
                        .HasColumnType("float")
                        .HasColumnName("3h30");

                    b.Property<double?>("_4h")
                        .HasColumnType("float")
                        .HasColumnName("4h");

                    b.Property<double?>("_4h30")
                        .HasColumnType("float")
                        .HasColumnName("4h30");

                    b.Property<double?>("_5h")
                        .HasColumnType("float")
                        .HasColumnName("5h");

                    b.Property<double?>("_5h30")
                        .HasColumnType("float")
                        .HasColumnName("5h30");

                    b.Property<double?>("_6h")
                        .HasColumnType("float")
                        .HasColumnName("6h");

                    b.Property<double?>("_6h30")
                        .HasColumnType("float")
                        .HasColumnName("6h30");

                    b.Property<double?>("_7h")
                        .HasColumnType("float")
                        .HasColumnName("7h");

                    b.Property<double?>("_7h30")
                        .HasColumnType("float")
                        .HasColumnName("7h30");

                    b.Property<double?>("_8h")
                        .HasColumnType("float")
                        .HasColumnName("8h");

                    b.Property<double?>("_8h30")
                        .HasColumnType("float")
                        .HasColumnName("8h30");

                    b.Property<double?>("_9h")
                        .HasColumnType("float")
                        .HasColumnName("9h");

                    b.Property<double?>("_9h30")
                        .HasColumnType("float")
                        .HasColumnName("9h30");

                    b.ToTable("' Qm1_Cspot1$ $'");
                });

            modelBuilder.Entity("CSPOT.Models.Qm2Dh3mrCspot2", b =>
                {
                    b.Property<DateTime?>("Ngày")
                        .HasColumnType("datetime");

                    b.Property<double?>("Tổng")
                        .HasColumnType("float");

                    b.Property<double?>("_0h30")
                        .HasColumnType("float")
                        .HasColumnName("0h30");

                    b.Property<double?>("_10h")
                        .HasColumnType("float")
                        .HasColumnName("10h");

                    b.Property<double?>("_10h30")
                        .HasColumnType("float")
                        .HasColumnName("10h30");

                    b.Property<double?>("_11h")
                        .HasColumnType("float")
                        .HasColumnName("11h");

                    b.Property<double?>("_11h30")
                        .HasColumnType("float")
                        .HasColumnName("11h30");

                    b.Property<double?>("_12h")
                        .HasColumnType("float")
                        .HasColumnName("12h");

                    b.Property<double?>("_12h30")
                        .HasColumnType("float")
                        .HasColumnName("12h30");

                    b.Property<double?>("_13h")
                        .HasColumnType("float")
                        .HasColumnName("13h");

                    b.Property<double?>("_13h30")
                        .HasColumnType("float")
                        .HasColumnName("13h30");

                    b.Property<double?>("_14h")
                        .HasColumnType("float")
                        .HasColumnName("14h");

                    b.Property<double?>("_14h30")
                        .HasColumnType("float")
                        .HasColumnName("14h30");

                    b.Property<double?>("_15h")
                        .HasColumnType("float")
                        .HasColumnName("15h");

                    b.Property<double?>("_15h30")
                        .HasColumnType("float")
                        .HasColumnName("15h30");

                    b.Property<double?>("_16h")
                        .HasColumnType("float")
                        .HasColumnName("16h");

                    b.Property<double?>("_16h30")
                        .HasColumnType("float")
                        .HasColumnName("16h30");

                    b.Property<double?>("_17h")
                        .HasColumnType("float")
                        .HasColumnName("17h");

                    b.Property<double?>("_17h30")
                        .HasColumnType("float")
                        .HasColumnName("17h30");

                    b.Property<double?>("_18h")
                        .HasColumnType("float")
                        .HasColumnName("18h");

                    b.Property<double?>("_18h30")
                        .HasColumnType("float")
                        .HasColumnName("18h30");

                    b.Property<double?>("_19h")
                        .HasColumnType("float")
                        .HasColumnName("19h");

                    b.Property<double?>("_19h30")
                        .HasColumnType("float")
                        .HasColumnName("19h30");

                    b.Property<double?>("_1h")
                        .HasColumnType("float")
                        .HasColumnName("1h");

                    b.Property<double?>("_1h30")
                        .HasColumnType("float")
                        .HasColumnName("1h30");

                    b.Property<double?>("_20h")
                        .HasColumnType("float")
                        .HasColumnName("20h");

                    b.Property<double?>("_20h30")
                        .HasColumnType("float")
                        .HasColumnName("20h30");

                    b.Property<double?>("_21h")
                        .HasColumnType("float")
                        .HasColumnName("21h");

                    b.Property<double?>("_21h30")
                        .HasColumnType("float")
                        .HasColumnName("21h30");

                    b.Property<double?>("_22h")
                        .HasColumnType("float")
                        .HasColumnName("22h");

                    b.Property<double?>("_22h30")
                        .HasColumnType("float")
                        .HasColumnName("22h30");

                    b.Property<double?>("_23h")
                        .HasColumnType("float")
                        .HasColumnName("23h");

                    b.Property<double?>("_23h30")
                        .HasColumnType("float")
                        .HasColumnName("23h30");

                    b.Property<double?>("_24h")
                        .HasColumnType("float")
                        .HasColumnName("24h");

                    b.Property<double?>("_2h")
                        .HasColumnType("float")
                        .HasColumnName("2h");

                    b.Property<double?>("_2h30")
                        .HasColumnType("float")
                        .HasColumnName("2h30");

                    b.Property<double?>("_3h")
                        .HasColumnType("float")
                        .HasColumnName("3h");

                    b.Property<double?>("_3h30")
                        .HasColumnType("float")
                        .HasColumnName("3h30");

                    b.Property<double?>("_4h")
                        .HasColumnType("float")
                        .HasColumnName("4h");

                    b.Property<double?>("_4h30")
                        .HasColumnType("float")
                        .HasColumnName("4h30");

                    b.Property<double?>("_5h")
                        .HasColumnType("float")
                        .HasColumnName("5h");

                    b.Property<double?>("_5h30")
                        .HasColumnType("float")
                        .HasColumnName("5h30");

                    b.Property<double?>("_6h")
                        .HasColumnType("float")
                        .HasColumnName("6h");

                    b.Property<double?>("_6h30")
                        .HasColumnType("float")
                        .HasColumnName("6h30");

                    b.Property<double?>("_7h")
                        .HasColumnType("float")
                        .HasColumnName("7h");

                    b.Property<double?>("_7h30")
                        .HasColumnType("float")
                        .HasColumnName("7h30");

                    b.Property<double?>("_8h")
                        .HasColumnType("float")
                        .HasColumnName("8h");

                    b.Property<double?>("_8h30")
                        .HasColumnType("float")
                        .HasColumnName("8h30");

                    b.Property<double?>("_9h")
                        .HasColumnType("float")
                        .HasColumnName("9h");

                    b.Property<double?>("_9h30")
                        .HasColumnType("float")
                        .HasColumnName("9h30");

                    b.ToTable("Qm2DH3MR_Cspot2$$");
                });

            modelBuilder.Entity("CSPOT.Models.Qm2TbCspot2", b =>
                {
                    b.Property<DateTime?>("Ngày")
                        .HasColumnType("datetime");

                    b.Property<double?>("Tổng")
                        .HasColumnType("float");

                    b.Property<double?>("_0h30")
                        .HasColumnType("float")
                        .HasColumnName("0h30");

                    b.Property<double?>("_10h")
                        .HasColumnType("float")
                        .HasColumnName("10h");

                    b.Property<double?>("_10h30")
                        .HasColumnType("float")
                        .HasColumnName("10h30");

                    b.Property<double?>("_11h")
                        .HasColumnType("float")
                        .HasColumnName("11h");

                    b.Property<double?>("_11h30")
                        .HasColumnType("float")
                        .HasColumnName("11h30");

                    b.Property<double?>("_12h")
                        .HasColumnType("float")
                        .HasColumnName("12h");

                    b.Property<double?>("_12h30")
                        .HasColumnType("float")
                        .HasColumnName("12h30");

                    b.Property<double?>("_13h")
                        .HasColumnType("float")
                        .HasColumnName("13h");

                    b.Property<double?>("_13h30")
                        .HasColumnType("float")
                        .HasColumnName("13h30");

                    b.Property<double?>("_14h")
                        .HasColumnType("float")
                        .HasColumnName("14h");

                    b.Property<double?>("_14h30")
                        .HasColumnType("float")
                        .HasColumnName("14h30");

                    b.Property<double?>("_15h")
                        .HasColumnType("float")
                        .HasColumnName("15h");

                    b.Property<double?>("_15h30")
                        .HasColumnType("float")
                        .HasColumnName("15h30");

                    b.Property<double?>("_16h")
                        .HasColumnType("float")
                        .HasColumnName("16h");

                    b.Property<double?>("_16h30")
                        .HasColumnType("float")
                        .HasColumnName("16h30");

                    b.Property<double?>("_17h")
                        .HasColumnType("float")
                        .HasColumnName("17h");

                    b.Property<double?>("_17h30")
                        .HasColumnType("float")
                        .HasColumnName("17h30");

                    b.Property<double?>("_18h")
                        .HasColumnType("float")
                        .HasColumnName("18h");

                    b.Property<double?>("_18h30")
                        .HasColumnType("float")
                        .HasColumnName("18h30");

                    b.Property<double?>("_19h")
                        .HasColumnType("float")
                        .HasColumnName("19h");

                    b.Property<double?>("_19h30")
                        .HasColumnType("float")
                        .HasColumnName("19h30");

                    b.Property<double?>("_1h")
                        .HasColumnType("float")
                        .HasColumnName("1h");

                    b.Property<double?>("_1h30")
                        .HasColumnType("float")
                        .HasColumnName("1h30");

                    b.Property<double?>("_20h")
                        .HasColumnType("float")
                        .HasColumnName("20h");

                    b.Property<double?>("_20h30")
                        .HasColumnType("float")
                        .HasColumnName("20h30");

                    b.Property<double?>("_21h")
                        .HasColumnType("float")
                        .HasColumnName("21h");

                    b.Property<double?>("_21h30")
                        .HasColumnType("float")
                        .HasColumnName("21h30");

                    b.Property<double?>("_22h")
                        .HasColumnType("float")
                        .HasColumnName("22h");

                    b.Property<double?>("_22h30")
                        .HasColumnType("float")
                        .HasColumnName("22h30");

                    b.Property<double?>("_23h")
                        .HasColumnType("float")
                        .HasColumnName("23h");

                    b.Property<double?>("_23h30")
                        .HasColumnType("float")
                        .HasColumnName("23h30");

                    b.Property<double?>("_24h")
                        .HasColumnType("float")
                        .HasColumnName("24h");

                    b.Property<double?>("_2h")
                        .HasColumnType("float")
                        .HasColumnName("2h");

                    b.Property<double?>("_2h30")
                        .HasColumnType("float")
                        .HasColumnName("2h30");

                    b.Property<double?>("_3h")
                        .HasColumnType("float")
                        .HasColumnName("3h");

                    b.Property<double?>("_3h30")
                        .HasColumnType("float")
                        .HasColumnName("3h30");

                    b.Property<double?>("_4h")
                        .HasColumnType("float")
                        .HasColumnName("4h");

                    b.Property<double?>("_4h30")
                        .HasColumnType("float")
                        .HasColumnName("4h30");

                    b.Property<double?>("_5h")
                        .HasColumnType("float")
                        .HasColumnName("5h");

                    b.Property<double?>("_5h30")
                        .HasColumnType("float")
                        .HasColumnName("5h30");

                    b.Property<double?>("_6h")
                        .HasColumnType("float")
                        .HasColumnName("6h");

                    b.Property<double?>("_6h30")
                        .HasColumnType("float")
                        .HasColumnName("6h30");

                    b.Property<double?>("_7h")
                        .HasColumnType("float")
                        .HasColumnName("7h");

                    b.Property<double?>("_7h30")
                        .HasColumnType("float")
                        .HasColumnName("7h30");

                    b.Property<double?>("_8h")
                        .HasColumnType("float")
                        .HasColumnName("8h");

                    b.Property<double?>("_8h30")
                        .HasColumnType("float")
                        .HasColumnName("8h30");

                    b.Property<double?>("_9h")
                        .HasColumnType("float")
                        .HasColumnName("9h");

                    b.Property<double?>("_9h30")
                        .HasColumnType("float")
                        .HasColumnName("9h30");

                    b.ToTable("Qm2TB_Cspot2$$");
                });

            modelBuilder.Entity("CSPOT.Models.Qm2Vt4Cspot2", b =>
                {
                    b.Property<DateTime?>("Ngày")
                        .HasColumnType("datetime");

                    b.Property<double?>("Tổng")
                        .HasColumnType("float");

                    b.Property<double?>("_0h30")
                        .HasColumnType("float")
                        .HasColumnName("0h30");

                    b.Property<double?>("_10h")
                        .HasColumnType("float")
                        .HasColumnName("10h");

                    b.Property<double?>("_10h30")
                        .HasColumnType("float")
                        .HasColumnName("10h30");

                    b.Property<double?>("_11h")
                        .HasColumnType("float")
                        .HasColumnName("11h");

                    b.Property<double?>("_11h30")
                        .HasColumnType("float")
                        .HasColumnName("11h30");

                    b.Property<double?>("_12h")
                        .HasColumnType("float")
                        .HasColumnName("12h");

                    b.Property<double?>("_12h30")
                        .HasColumnType("float")
                        .HasColumnName("12h30");

                    b.Property<double?>("_13h")
                        .HasColumnType("float")
                        .HasColumnName("13h");

                    b.Property<double?>("_13h30")
                        .HasColumnType("float")
                        .HasColumnName("13h30");

                    b.Property<double?>("_14h")
                        .HasColumnType("float")
                        .HasColumnName("14h");

                    b.Property<double?>("_14h30")
                        .HasColumnType("float")
                        .HasColumnName("14h30");

                    b.Property<double?>("_15h")
                        .HasColumnType("float")
                        .HasColumnName("15h");

                    b.Property<double?>("_15h30")
                        .HasColumnType("float")
                        .HasColumnName("15h30");

                    b.Property<double?>("_16h")
                        .HasColumnType("float")
                        .HasColumnName("16h");

                    b.Property<double?>("_16h30")
                        .HasColumnType("float")
                        .HasColumnName("16h30");

                    b.Property<double?>("_17h")
                        .HasColumnType("float")
                        .HasColumnName("17h");

                    b.Property<double?>("_17h30")
                        .HasColumnType("float")
                        .HasColumnName("17h30");

                    b.Property<double?>("_18h")
                        .HasColumnType("float")
                        .HasColumnName("18h");

                    b.Property<double?>("_18h30")
                        .HasColumnType("float")
                        .HasColumnName("18h30");

                    b.Property<double?>("_19h")
                        .HasColumnType("float")
                        .HasColumnName("19h");

                    b.Property<double?>("_19h30")
                        .HasColumnType("float")
                        .HasColumnName("19h30");

                    b.Property<double?>("_1h")
                        .HasColumnType("float")
                        .HasColumnName("1h");

                    b.Property<double?>("_1h30")
                        .HasColumnType("float")
                        .HasColumnName("1h30");

                    b.Property<double?>("_20h")
                        .HasColumnType("float")
                        .HasColumnName("20h");

                    b.Property<double?>("_20h30")
                        .HasColumnType("float")
                        .HasColumnName("20h30");

                    b.Property<double?>("_21h")
                        .HasColumnType("float")
                        .HasColumnName("21h");

                    b.Property<double?>("_21h30")
                        .HasColumnType("float")
                        .HasColumnName("21h30");

                    b.Property<double?>("_22h")
                        .HasColumnType("float")
                        .HasColumnName("22h");

                    b.Property<double?>("_22h30")
                        .HasColumnType("float")
                        .HasColumnName("22h30");

                    b.Property<double?>("_23h")
                        .HasColumnType("float")
                        .HasColumnName("23h");

                    b.Property<double?>("_23h30")
                        .HasColumnType("float")
                        .HasColumnName("23h30");

                    b.Property<double?>("_24h")
                        .HasColumnType("float")
                        .HasColumnName("24h");

                    b.Property<double?>("_2h")
                        .HasColumnType("float")
                        .HasColumnName("2h");

                    b.Property<double?>("_2h30")
                        .HasColumnType("float")
                        .HasColumnName("2h30");

                    b.Property<double?>("_3h")
                        .HasColumnType("float")
                        .HasColumnName("3h");

                    b.Property<double?>("_3h30")
                        .HasColumnType("float")
                        .HasColumnName("3h30");

                    b.Property<double?>("_4h")
                        .HasColumnType("float")
                        .HasColumnName("4h");

                    b.Property<double?>("_4h30")
                        .HasColumnType("float")
                        .HasColumnName("4h30");

                    b.Property<double?>("_5h")
                        .HasColumnType("float")
                        .HasColumnName("5h");

                    b.Property<double?>("_5h30")
                        .HasColumnType("float")
                        .HasColumnName("5h30");

                    b.Property<double?>("_6h")
                        .HasColumnType("float")
                        .HasColumnName("6h");

                    b.Property<double?>("_6h30")
                        .HasColumnType("float")
                        .HasColumnName("6h30");

                    b.Property<double?>("_7h")
                        .HasColumnType("float")
                        .HasColumnName("7h");

                    b.Property<double?>("_7h30")
                        .HasColumnType("float")
                        .HasColumnName("7h30");

                    b.Property<double?>("_8h")
                        .HasColumnType("float")
                        .HasColumnName("8h");

                    b.Property<double?>("_8h30")
                        .HasColumnType("float")
                        .HasColumnName("8h30");

                    b.Property<double?>("_9h")
                        .HasColumnType("float")
                        .HasColumnName("9h");

                    b.Property<double?>("_9h30")
                        .HasColumnType("float")
                        .HasColumnName("9h30");

                    b.ToTable("Qm2VT4_Cspot2$$");
                });

            modelBuilder.Entity("CSPOT.Models.Qm2Vt4mrCspot2", b =>
                {
                    b.Property<DateTime?>("Ngày")
                        .HasColumnType("datetime");

                    b.Property<double?>("Tổng")
                        .HasColumnType("float");

                    b.Property<double?>("_0h30")
                        .HasColumnType("float")
                        .HasColumnName("0h30");

                    b.Property<double?>("_10h")
                        .HasColumnType("float")
                        .HasColumnName("10h");

                    b.Property<double?>("_10h30")
                        .HasColumnType("float")
                        .HasColumnName("10h30");

                    b.Property<double?>("_11h")
                        .HasColumnType("float")
                        .HasColumnName("11h");

                    b.Property<double?>("_11h30")
                        .HasColumnType("float")
                        .HasColumnName("11h30");

                    b.Property<double?>("_12h")
                        .HasColumnType("float")
                        .HasColumnName("12h");

                    b.Property<double?>("_12h30")
                        .HasColumnType("float")
                        .HasColumnName("12h30");

                    b.Property<double?>("_13h")
                        .HasColumnType("float")
                        .HasColumnName("13h");

                    b.Property<double?>("_13h30")
                        .HasColumnType("float")
                        .HasColumnName("13h30");

                    b.Property<double?>("_14h")
                        .HasColumnType("float")
                        .HasColumnName("14h");

                    b.Property<double?>("_14h30")
                        .HasColumnType("float")
                        .HasColumnName("14h30");

                    b.Property<double?>("_15h")
                        .HasColumnType("float")
                        .HasColumnName("15h");

                    b.Property<double?>("_15h30")
                        .HasColumnType("float")
                        .HasColumnName("15h30");

                    b.Property<double?>("_16h")
                        .HasColumnType("float")
                        .HasColumnName("16h");

                    b.Property<double?>("_16h30")
                        .HasColumnType("float")
                        .HasColumnName("16h30");

                    b.Property<double?>("_17h")
                        .HasColumnType("float")
                        .HasColumnName("17h");

                    b.Property<double?>("_17h30")
                        .HasColumnType("float")
                        .HasColumnName("17h30");

                    b.Property<double?>("_18h")
                        .HasColumnType("float")
                        .HasColumnName("18h");

                    b.Property<double?>("_18h30")
                        .HasColumnType("float")
                        .HasColumnName("18h30");

                    b.Property<double?>("_19h")
                        .HasColumnType("float")
                        .HasColumnName("19h");

                    b.Property<double?>("_19h30")
                        .HasColumnType("float")
                        .HasColumnName("19h30");

                    b.Property<double?>("_1h")
                        .HasColumnType("float")
                        .HasColumnName("1h");

                    b.Property<double?>("_1h30")
                        .HasColumnType("float")
                        .HasColumnName("1h30");

                    b.Property<double?>("_20h")
                        .HasColumnType("float")
                        .HasColumnName("20h");

                    b.Property<double?>("_20h30")
                        .HasColumnType("float")
                        .HasColumnName("20h30");

                    b.Property<double?>("_21h")
                        .HasColumnType("float")
                        .HasColumnName("21h");

                    b.Property<double?>("_21h30")
                        .HasColumnType("float")
                        .HasColumnName("21h30");

                    b.Property<double?>("_22h")
                        .HasColumnType("float")
                        .HasColumnName("22h");

                    b.Property<double?>("_22h30")
                        .HasColumnType("float")
                        .HasColumnName("22h30");

                    b.Property<double?>("_23h")
                        .HasColumnType("float")
                        .HasColumnName("23h");

                    b.Property<double?>("_23h30")
                        .HasColumnType("float")
                        .HasColumnName("23h30");

                    b.Property<double?>("_24h")
                        .HasColumnType("float")
                        .HasColumnName("24h");

                    b.Property<double?>("_2h")
                        .HasColumnType("float")
                        .HasColumnName("2h");

                    b.Property<double?>("_2h30")
                        .HasColumnType("float")
                        .HasColumnName("2h30");

                    b.Property<double?>("_3h")
                        .HasColumnType("float")
                        .HasColumnName("3h");

                    b.Property<double?>("_3h30")
                        .HasColumnType("float")
                        .HasColumnName("3h30");

                    b.Property<double?>("_4h")
                        .HasColumnType("float")
                        .HasColumnName("4h");

                    b.Property<double?>("_4h30")
                        .HasColumnType("float")
                        .HasColumnName("4h30");

                    b.Property<double?>("_5h")
                        .HasColumnType("float")
                        .HasColumnName("5h");

                    b.Property<double?>("_5h30")
                        .HasColumnType("float")
                        .HasColumnName("5h30");

                    b.Property<double?>("_6h")
                        .HasColumnType("float")
                        .HasColumnName("6h");

                    b.Property<double?>("_6h30")
                        .HasColumnType("float")
                        .HasColumnName("6h30");

                    b.Property<double?>("_7h")
                        .HasColumnType("float")
                        .HasColumnName("7h");

                    b.Property<double?>("_7h30")
                        .HasColumnType("float")
                        .HasColumnName("7h30");

                    b.Property<double?>("_8h")
                        .HasColumnType("float")
                        .HasColumnName("8h");

                    b.Property<double?>("_8h30")
                        .HasColumnType("float")
                        .HasColumnName("8h30");

                    b.Property<double?>("_9h")
                        .HasColumnType("float")
                        .HasColumnName("9h");

                    b.Property<double?>("_9h30")
                        .HasColumnType("float")
                        .HasColumnName("9h30");

                    b.ToTable("'Qm2VT4MR-Cspot2$$'");
                });

            modelBuilder.Entity("CSPOT.Models.TongHopCspot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long?>("ChiPhiCm1")
                        .HasColumnType("bigint")
                        .HasColumnName("chi_phi_cm1");

                    b.Property<long?>("ChiPhiCm2")
                        .HasColumnType("bigint")
                        .HasColumnName("chi_phi_cm2");

                    b.Property<long?>("ChiPhiDh3Mr")
                        .HasColumnType("bigint")
                        .HasColumnName("chi_phi_dh3_mr");

                    b.Property<long?>("ChiPhiTb")
                        .HasColumnType("bigint")
                        .HasColumnName("chi_phi_tb");

                    b.Property<long?>("ChiPhiVt4")
                        .HasColumnType("bigint")
                        .HasColumnName("chi_phi_vt4");

                    b.Property<long?>("ChiPhiVt4Mr")
                        .HasColumnType("bigint")
                        .HasColumnName("chi_phi_vt4_mr");

                    b.Property<DateTime?>("Ngay")
                        .HasColumnType("datetime")
                        .HasColumnName("ngay");

                    b.Property<long?>("SanLuongDh3Mr")
                        .HasColumnType("bigint")
                        .HasColumnName("san_luong_dh3_mr");

                    b.Property<long?>("SanLuongQm")
                        .HasColumnType("bigint")
                        .HasColumnName("san_luong_qm");

                    b.Property<long?>("SanLuongQm1")
                        .HasColumnType("bigint")
                        .HasColumnName("san_luong_qm1");

                    b.Property<long?>("SanLuongQm2")
                        .HasColumnType("bigint")
                        .HasColumnName("san_luong_qm2");

                    b.Property<long?>("SanLuongTb")
                        .HasColumnType("bigint")
                        .HasColumnName("san_luong_tb");

                    b.Property<long?>("SanLuongVt4")
                        .HasColumnType("bigint")
                        .HasColumnName("san_luong_vt4");

                    b.Property<long?>("SanLuongVt4Mr")
                        .HasColumnType("bigint")
                        .HasColumnName("san_luong_vt4_mr");

                    b.Property<long?>("TongChiPhi")
                        .HasColumnType("bigint")
                        .HasColumnName("tong_chi_phi");

                    b.HasKey("Id")
                        .HasName("PK__TongHopC__3214EC2791524868");

                    b.ToTable("TongHopCspot");
                });

            modelBuilder.Entity("CSPOT.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
